import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { ItemDto } from '../../_autogenerated/itemDto';
import { Store, select } from '@ngrx/store';
import { ItemsState } from '../state/reducer';
import { getSelectedItem } from '../state/index'

@Component({
  selector: 'compA',
  templateUrl: './compA.component.html',
  styleUrls: ['./compA.component.scss']
})
export class CompAComponent implements OnInit {

  public item$: Observable<ItemDto>;
  constructor(private store: Store<ItemsState>) { }

  ngOnInit() {
    this.item$ = this.store.pipe(select(getSelectedItem));
  }

}
