import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { GalleryApiService } from "../_autogenerated/galleryApi.service";
import { FileBindingModel } from "../_autogenerated/fileBindingModel";
import { FileDto } from "../_autogenerated/fileDto";

@Injectable({ providedIn: 'root' })
export class GalleryService {

    constructor(
        private httpClient: HttpClient,
        private galleryApiService: GalleryApiService) {
    }

    public uploadFiles = (model: FileBindingModel[]) =>
        this.httpClient.post(this.galleryApiService.Url_UploadFile(), model);

    public getUploadedFiles = () =>
        this.httpClient.get<FileDto[]>(this.galleryApiService.Url_GetUploadedFiles());

    public getFile = (fileName:string) =>
        this.httpClient.get(this.galleryApiService.Url_GetFile(fileName));

    public deleteFile = (fileName: string) =>
        this.httpClient.delete(this.galleryApiService.Url_DeleteFile(fileName));

    public getFileUrl = (fileName: string) =>
        this.galleryApiService.Url_GetFile(fileName);


}