import { Observable, of } from "rxjs";
import { Injectable } from "@angular/core";
import { ItemService } from "../item.service";
import { map, catchError } from "rxjs/operators";
import { ItemDto } from "../../_autogenerated/itemDto";
import {  ActivatedRouteSnapshot, RouterStateSnapshot, Resolve } from "@angular/router";

@Injectable({
    providedIn: 'root'
})
export class ItemDetailsResolver implements Resolve<ItemDto> {

    constructor(
        private itemService: ItemService,
    ) { }

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<ItemDto | any> {
            return this.itemService.getItem(+route.params['id']).pipe(
                map(item => item),
                catchError(error => {
                    return of(null);
                })
            )}

    
}